name: json_placeholder
description: Test task.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  dio: ^5.0.3
  either_dart: ^0.3.0
  go_router: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

assets:
  - assets/images/
